SELECT * FROM EMPLOYEES ;

-- FIND OUT ALL THE EMPLOYEES WITH DEPARTMENT ID OF 60 OR 100

SELECT * FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60 OR DEPARTMENT_ID = 100; 

-- ONLY GET FIRST_NAME AND LAST_NAME AND SALARY AND JOB_ID

SELECT FIRST_NAME, LAST_NAME, SALARY, JOB_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60 OR DEPARTMENT_ID = 100; 

-- >, >=, =, !=, <>, >=
-- AND, OR

-- FIND OUT ALL THE JOBS INFORMATION IF THE MINIMUM SALARY IS MORE THAN 5500 AND LESS THAN 10000
-- USE JOBS TABLE

SELECT * FROM JOBS
--WHERE MIN_SALARY BETWEEN 5500 AND 10000;
WHERE MIN_SALARY >= 5000 AND MIN_SALARY <= 10000;

-- FIND OUT ALL THE EMPLOYEES FIRST NAME AND PHONE AND DEPARTMENT_ID
-- WITH DEPARTMENT ID OF 60 OR 100 OR 90 OR 80 OR 120
-- IF WE ARE CHECKING FOR MULTIPLE POSSIBLE VALUES FAOR SAME COLUMN
-- WE CAN USE IN (VALUE1, VALUE2, VALUE3......)


SELECT FIRST_NAME, PHONE_NUMBER, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID IN (60, 100, 90,80, 120); 

-- ABOVE QUERY IS AS SAME AS BELOW QUERY USING OR
SELECT FIRST_NAME, PHONE_NUMBER, DEPARTMENT_ID
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 60 OR
        DEPARTMENT_ID = 100 OR
        DEPARTMENT_ID = 90 OR
        DEPARTMENT_ID = 80 OR
        DEPARTMENT_ID = 120 ;

-- I WANT TO GET ALL THE FIRST NAME THAT START WITH LETTER A
-- FROM EMPLOYEE TABLE
-- % IS WILD CARD that can represent 0 or more characters
-- for example 'A%' means --> any String that starts with letter A
-- WE CAN USE IT TO PARTIAL STRING MATCH

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%'
;

-- I WANT TO GET ALL THE FIRST NAME THAT ENDS WITH LETTER a
--%a
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a';

-- FIND OUT ALL FIRST NAME AND LAST NAME FROM EMPLOYEES TABLE
-- IF THE FIRST NAME STARTS WITH A AND LAST NAME END WITH n
SELECT FIRST_NAME, LAST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE 'A%' AND LAST_NAME LIKE '%n'; 

-- FIND OUT ALL THE NAMES THAT CONTAIN letter a, anywhere
-- '%a%' means a can be anywhere

SELECT FIRST_NAME
FROM EMPLOYEES
WHERE FIRST_NAME LIKE '%a%'; 

--find out all job_id start with AD

SELECT JOB_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE 'AD%' ;
--find out all job_id end with REP
SELECT JOB_ID
FROM EMPLOYEES
WHERE JOB_ID LIKE '%REP'  ;

--FIND OUT ALL THE JOB ID FROM EMPLOYEE TABLE THAT DOES NOT END WITH REP
SELECT JOB_ID
FROM EMPLOYEES
WHERE JOB_ID NOT LIKE '%REP'  ;

--FIND OUT ALL THE FIRST NAME THAT DOES NOT CONTAIN LETTER a
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE JOB_ID NOT LIKE '%a%'  ;

-- MAKE ABOVE QUER CASE INSENSITIVE
--FIRST_NAME DOES NOT CONTAIN a AND DOES NOT STRAT WITH A
SELECT FIRST_NAME
FROM EMPLOYEES
WHERE JOB_ID NOT LIKE '%a%' AND FIRST_NAME NOT LIKE 'A&' ;

--WORKING WITH NULL VALUE
-- IF A CELL HAS NO VALUE ENTERED IT'S NULL

-- FIND OUT THE EMPLOYEE INFORMATION IF THE EMPLOYEES MANAGER_ID IS NULL
SELECT * FROM EMPLOYEES
WHERE MANAGER_ID IS NULL;

-- FIND OUT FIRST_NAME AND MANAGER_ID IS NOT NULL
SELECT FIRST_NAME, MANAGER_ID
FROM EMPLOYEES
WHERE MANAGER_ID IS NOT NULL;

--FUNCTIONS IN SQL -- PRE-WRITTEN FUNCTIONALITY WE CAN DIRECTLY USE - 2 TYPES
-- SINGLE ROW FUNCTION | GROUP FUNCTION | AGGREGATE FUNCTION

-- DISPLAY ALL EMPLOYEES FIRST NAME IN UPPER CASE /OWER CASE

SELECT FIRST_NAME , UPPER(FIRST_NAME) AS UPPERCASENAMES, LOWER(FIRST_NAME) AS LowerCaseNames
FROM EMPLOYEES;
SELECT FIRST_NAME , LOWER(FIRST_NAME)
FROM EMPLOYEES;

-- RETURN ALL EMPLOYEES FIRST NAME AND SALARY FROM EMPLOYEE TABLE
-- DISPLAY RESULTING COLUMN AS, NAME, MONEY
-- WE CAN GIVE ALIAS TO THE RESULTING QUERY RRESULT COLUMN NAME USING AS
SELECT FIRST_NAME AS NAME, SALARY AS MONEY
FROM EMPLOYEES;

-- I WANT TO RETURN FIRST_NAME AND LAST_NAME IN OINE COLUMN AND NAME THIS COLUMN AS FULL_NAME
--THE RESULT SHOULD BE 3 COLUMNS, FIRST_NAME, LAST_NAME AS FULL NAME

--CONCETANATION IN SQL USE ||
SELECT FIRST_NAME, LAST_NAME, FIRST_NAME || ' ' || LAST_NAME AS FULL_NAME
FROM EMPLOYEES;

-- I Love SQL Already LaLaLa
-- FIND OUT ALL THE FIRST NAME DOES NOT CONTAIN LETTER A OR a
SELECT FIRST_NAME, UPPER(FIRST_NAME)
FROM EMPLOYEES
WHERE UPPER(FIRST_NAME) LIKE '%A%' ;

SELECT FIRST_NAME 
FROM EMPLOYEES 
WHERE LOWER(FIRST_NAME) LIKE '%a%'
; 


--FIND OUT ALL THE FIRST NAME DOES NOT CONTAIN LETTER A or a 
SELECT FIRST_NAME , UPPER(FIRST_NAME)
FROM EMPLOYEES 
WHERE UPPER(FIRST_NAME) NOT LIKE '%A%'
; 

--- DISPLAY FIRST 3 LETTERS OF FIRST NAME 
-- substr(value, begIndex, endIndex)
SELECT FIRST_NAME ,  SUBSTR(FIRST_NAME, 1 , 3 ) , LENGTH(FIRST_NAME)
FROM EMPLOYEES ; 

-- MULTI ROW FUNCTION 